/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    // RCC
    uint32_t *RCC_AHB1ENR = (uint32_t *)0x40023830;

    // Enable GPIOB and GPIOC clocks
    *RCC_AHB1ENR |= (1 << 1);
    *RCC_AHB1ENR |= (1 << 2);


    // GPIOB MODER
    uint32_t *GPIOB_MODER = (uint32_t *)0x40020400;

    // PB13 = Output
    *GPIOB_MODER &= ~(3 << 26);
    *GPIOB_MODER |=  (1 << 26);


    // GPIOB ODR
    uint32_t *GPIOB_ODR = (uint32_t *)0x40020414;


    // GPIOC MODER
    uint32_t *GPIOC_MODER = (uint32_t *)0x40020800;

    // PC13 = Input
    *GPIOC_MODER &= ~(3 << 26);


    // GPIOC IDR
    uint32_t *GPIOC_IDR = (uint32_t *)0x40020810;


    while (1)
    {
        if (*GPIOC_IDR & (1 << 13))
        {
            // Button HIGH
            *GPIOB_ODR |= (1 << 13);
        }
        else
        {
            // Button LOW
            *GPIOB_ODR &= ~(1 << 13);
        }
    }
}
