/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    // Enable GPIOB clock
    uint32_t *RCC_AHB1ENR = (uint32_t *)0x40023830;
    *RCC_AHB1ENR |= (1 << 1);

    // GPIOB MODER
    uint32_t *GPIOB_MODER = (uint32_t *)0x40020400;
    *GPIOB_MODER &= ~(3 << 26);
    *GPIOB_MODER |=  (1 << 26);

    // GPIOB ODR
    uint32_t *GPIOB_ODR = (uint32_t *)0x40020414;

    while(1)
    {
        *GPIOB_ODR ^= (1 << 13);

        for(volatile uint32_t i = 0; i < 500000; i++);
    }
}
/*#include <stdint.h>


int main(void)
{
    /* Loop forever
	uint32_t *prccgpiob=(uint32_t*)(0x40023800+0x30);//this address boundary address from mmory map abh1
	*prccgpiob|=0x01;
	uint32_t *pgpio_b=(uint32_t*)(0x40020400+0x00);//this is base address from reference manual of gpio b
	*pgpio_b &=(0xF3FFFFFF);
	*pgpio_b|=0x01<<26;
	uint32_t *prccgpiostate=(uint32_t*)(0x40023800+0x14);
	*prccgpiostate|=0x01<<13;
	for(;;);
}
when im running this in proteus then im not getting any blink*/
